const $=s=>document.querySelector(s);
const allowedEmail=/^[A-Z0-9._%+-]+@moh\.gov\.sa$/i;
const state={email:"",messages:[]};
const knowledge=[
 {keys:["معرف","هوية","تحقق","الاسم","رقم الملف","تاريخ الميلاد"],answer:"يجب التحقق من هوية المريض باستخدام معرّفين فريدين على الأقل. تشمل البيانات المعتمدة الاسم الكامل ورقم السجل الطبي، مع التحقق كذلك من تاريخ الميلاد والعمر حسب الإجراء. لا يجوز استخدام رقم الغرفة أو السرير للتعريف بالمريض.",section:"Correct Patient Identification Policy — البنود 2.6، 3.5، 4.3"},
 {keys:["رفض","السوار","ارتداء"],answer:"إذا رفض المريض ارتداء سوار التعريف، يجب شرح المخاطر له وتوثيق النقاش وسبب الرفض في السجل الطبي. ثم تُستخدم وسيلة تعريف بديلة مناسبة بعد موافقة المريض أو قريبه، مع زيادة اليقظة قبل أي إجراء أو تدخل.",section:"Correct Patient Identification Policy — البنود 4.26.7 و4.27"},
 {keys:["فاقد","وعي","مجهول","غيبوبة"],answer:"يُسجّل المريض المجهول أو فاقد الوعي بنظام ترقيم مثل UNKNOWN #1 متبوعًا برقم سجل طبي فريد، ويجب أن يرتدي سوار تعريف. إذا تعذر عليه تأكيد هويته، يتحقق ممرضَان مسجلان من الهوية قبل وضع السوار، ما لم يوجد ممثل يعرف المريض جيدًا.",section:"Correct Patient Identification Policy — البنود 4.9 إلى 4.11 و4.26.5"},
 {keys:["نقل","تحويل","مسرح","عملية"],answer:"عند النقل الداخلي يتحقق المستلم من سوار المريض ويراجع السجل الطبي. وعند استقبال مريض من منشأة أخرى يوضع سوار المنشأة المستقبلة فور وصوله ويزال السوار السابق. قبل الإجراء الجراحي يتم التحقق النهائي ضمن عملية الـ Time-Out.",section:"Correct Patient Identification Policy — البنود 4.15 إلى 4.18"}
];
function key(email){return `lumacare:${email.toLowerCase()}`}
function save(){localStorage.setItem(key(state.email),JSON.stringify(state.messages))}
function load(){try{state.messages=JSON.parse(localStorage.getItem(key(state.email))||"[]")}catch{state.messages=[]}renderMessages();renderHistory()}
function login(email){state.email=email.toLowerCase();localStorage.setItem("lumacare:lastUser",state.email);$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#profileEmail").textContent=state.email;$("#avatar").textContent=state.email[0].toUpperCase();load()}
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();const email=$("#email").value.trim();if(!allowedEmail.test(email)){$("#emailError").textContent="البريد غير مقبول";$("#emailField").classList.add("invalid");return}$("#emailError").textContent="";$("#emailField").classList.remove("invalid");login(email)});
$("#email").addEventListener("input",()=>{$("#emailError").textContent="";$("#emailField").classList.remove("invalid")});
function renderMessages(){const box=$("#messages");if(!state.messages.length){box.innerHTML=`<article class="welcome-message"><div class="spark">✦</div><h2>أهلًا بك في LumaCare</h2><p>اسأل عن سياسة التعرف الصحيح على المريض، وسأجيبك مع الإشارة إلى المصدر.</p><div class="suggestions"><button>ما المعرّفات المطلوبة للتحقق من هوية المريض؟</button><button>ماذا نفعل إذا رفض المريض ارتداء سوار التعريف؟</button><button>كيف يتم تعريف المريض فاقد الوعي؟</button></div></article>`;wireSuggestions();return}box.innerHTML=state.messages.map(m=>`<article class="message ${m.role}">${escapeHtml(m.text)}${m.source?`<span class="citation">المصدر: ${escapeHtml(m.source)}</span>`:""}</article>`).join("");box.scrollTop=box.scrollHeight}
function answer(q){const normalized=q.toLowerCase();let best=null,score=0;for(const item of knowledge){const s=item.keys.filter(k=>normalized.includes(k)).length;if(s>score){score=s;best=item}}return best&&score?best:{answer:"لم أجد إجابة مؤكدة لهذا السؤال في الملفات المعتمدة حاليًا. أرسل ملفًا يغطي الموضوع أو أعد صياغة السؤال حول سياسة تعريف المريض.",section:"لا يوجد مصدر مطابق"}}
function ask(text){const q=text.trim();if(!q)return;state.messages.push({role:"user",text:q});const a=answer(q);state.messages.push({role:"assistant",text:a.answer,source:a.section});save();renderMessages();renderHistory()}
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();ask($("#question").value);$("#question").value=""});$("#question").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#chatForm").requestSubmit()}});
function wireSuggestions(){document.querySelectorAll(".suggestions button").forEach(b=>b.onclick=()=>ask(b.textContent))}
function renderHistory(){const userQs=state.messages.filter(m=>m.role==="user");$("#historyList").innerHTML=userQs.length?userQs.slice(-8).reverse().map(m=>`<button class="history-item">${escapeHtml(m.text)}</button>`).join(""):`<div style="color:#657c8c;font-size:12px;padding:10px">لا توجد محادثات بعد</div>`}
$("#newChat").onclick=()=>{state.messages=[];save();renderMessages();renderHistory()};$("#clearHistory").onclick=()=>{if(confirm("هل تريد مسح سجل المحادثات؟")){state.messages=[];save();renderMessages();renderHistory()}};$("#logout").onclick=()=>{state.email="";state.messages=[];localStorage.removeItem("lumacare:lastUser");$("#appView").classList.add("hidden");$("#loginView").classList.remove("hidden")};
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
const last=localStorage.getItem("lumacare:lastUser");if(last&&allowedEmail.test(last))login(last);else wireSuggestions();

