const $=s=>document.querySelector(s);
const allowedEmail=/^[A-Z0-9._%+-]+@moh\.gov\.sa$/i;
const state={email:"",messages:[]};
const knowledge=[
 {terms:["معرف","هويه","تحقق","تاكد","اسم","رقم السجل","رقم الملف","تاريخ الميلاد","identify","identification","identifier","verify","verification","full name","medical record","mrn","date of birth","dob","room number","bed number"],ar:"يجب التحقق من هوية المريض باستخدام معرّفين فريدين على الأقل. تشمل البيانات المعتمدة الاسم الكامل ورقم السجل الطبي، مع التحقق كذلك من تاريخ الميلاد والعمر حسب الإجراء. لا يجوز استخدام رقم الغرفة أو السرير للتعريف بالمريض.",en:"The patient must be identified using at least two unique identifiers. Approved details include the patient's full name and medical record number, with date of birth and age also checked as required. A room or bed number must never be used to identify a patient.",section:"Correct Patient Identification Policy — Sections 2.6, 3.5 and 4.3"},
 {terms:["رفض","يرفض","السوار","الاسوره","ارتداء","ما يبي","رفض المريض","refuse","refuses","refusal","wristband","id band","declines","does not want","will not wear"],ar:"إذا رفض المريض ارتداء سوار التعريف، يجب شرح المخاطر له وتوثيق النقاش وسبب الرفض في السجل الطبي. ثم تُستخدم وسيلة تعريف بديلة مناسبة بعد موافقة المريض أو قريبه، مع زيادة اليقظة قبل أي إجراء أو تدخل.",en:"If a patient refuses an identification wristband, explain the risks and document the discussion and reason for refusal in the health record. Use an appropriate alternative identification method with consent and apply increased vigilance before any procedure or intervention.",section:"Correct Patient Identification Policy — Sections 4.26.7 and 4.27"},
 {terms:["فاقد","وعي","مجهول","غيبوبه","ما يتكلم","غير معروف","لا يستجيب","unconscious","unknown patient","unresponsive","comatose","coma","cannot respond","unable to identify","trauma patient"],ar:"يُسجّل المريض المجهول أو فاقد الوعي بنظام ترقيم مثل UNKNOWN #1 متبوعًا برقم سجل طبي فريد، ويجب أن يرتدي سوار تعريف. إذا تعذر عليه تأكيد هويته، يتحقق ممرضَان مسجلان من الهوية قبل وضع السوار، ما لم يوجد ممثل يعرف المريض جيدًا.",en:"An unknown or unconscious patient is registered using a numbering system such as UNKNOWN #1 followed by a unique medical record number and must wear an identification wristband. If the patient cannot confirm their identity, two registered nurses verify it before the band is applied unless a representative who knows the patient is present.",section:"Correct Patient Identification Policy — Sections 4.9–4.11 and 4.26.5"},
 {terms:["نقل","تحويل","مسرح","عمليه","جراحه","تايم اوت","بين الاقسام","transfer","transport","operating theatre","operating room","surgery","surgical","time out","another facility","receiving staff"],ar:"عند النقل الداخلي يتحقق المستلم من سوار المريض ويراجع السجل الطبي. وعند استقبال مريض من منشأة أخرى يوضع سوار المنشأة المستقبلة فور وصوله ويزال السوار السابق. قبل الإجراء الجراحي يتم التحقق النهائي ضمن عملية الـ Time-Out.",en:"During an internal transfer, the receiving staff member checks the patient's wristband and reviews the medical record. A patient arriving from another facility receives the new facility's wristband immediately and the previous band is removed. Final verification is completed during the Time-Out immediately before a procedure.",section:"Correct Patient Identification Policy — Sections 4.15–4.18"}
];
function key(email){return `lumacare:${email.toLowerCase()}`}
function save(){localStorage.setItem(key(state.email),JSON.stringify(state.messages))}
function load(){try{state.messages=JSON.parse(localStorage.getItem(key(state.email))||"[]")}catch{state.messages=[]}renderMessages();renderHistory()}
function login(email){state.email=email.toLowerCase();localStorage.setItem("lumacare:lastUser",state.email);$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#profileEmail").textContent=state.email;$("#avatar").textContent=state.email[0].toUpperCase();load()}
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();const email=$("#email").value.trim();if(!allowedEmail.test(email)){$("#emailError").textContent="البريد غير مقبول";$("#emailField").classList.add("invalid");return}$("#emailError").textContent="";$("#emailField").classList.remove("invalid");login(email)});
$("#email").addEventListener("input",()=>{$("#emailError").textContent="";$("#emailField").classList.remove("invalid")});
function renderMessages(){const box=$("#messages");if(!state.messages.length){box.innerHTML=`<article class="welcome-message"><div class="spark">✦</div><h2>أهلًا بك في LumaCare</h2><p>اسأل عن سياسة التعرف الصحيح على المريض، وسأجيبك مع الإشارة إلى المصدر.</p><div class="suggestions"><button>ما المعرّفات المطلوبة للتحقق من هوية المريض؟</button><button>ماذا نفعل إذا رفض المريض ارتداء سوار التعريف؟</button><button>كيف يتم تعريف المريض فاقد الوعي؟</button></div></article>`;wireSuggestions();return}box.innerHTML=state.messages.map(m=>`<article class="message ${m.role}">${escapeHtml(m.text)}${m.source?`<span class="citation">المصدر: ${escapeHtml(m.source)}</span>`:""}</article>`).join("");box.scrollTop=box.scrollHeight}
function normalizeText(value){return value.toLowerCase().normalize("NFKD").replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[^a-z0-9\u0600-\u06ff\s]/g," ").replace(/\s+/g," ").trim()}
function isArabic(value){return (value.match(/[\u0600-\u06ff]/g)||[]).length>(value.match(/[a-z]/gi)||[]).length}
function answer(q){const normalized=normalizeText(q);const words=normalized.split(" ").filter(w=>w.length>2);let best=null,score=0;for(const item of knowledge){let s=0;for(const rawTerm of item.terms){const term=normalizeText(rawTerm);if(normalized.includes(term))s+=term.includes(" ")?4:2;else if(words.some(word=>term.length>3&&(word.startsWith(term.slice(0,4))||term.startsWith(word.slice(0,4)))))s+=1}if(s>score){score=s;best=item}}const ar=isArabic(q);if(best&&score>=2)return{answer:ar?best.ar:best.en,section:best.section};return ar?{answer:"لم أجد إجابة مؤكدة لهذا السؤال في الملفات المعتمدة حاليًا. جرّب صياغة أخرى أو أرسل ملفًا يغطي الموضوع.",section:"لا يوجد مصدر مطابق"}:{answer:"I could not find a confirmed answer to this question in the currently approved files. Try another wording or provide a source document that covers the topic.",section:"No matching source"}}
function ask(text){const q=text.trim();if(!q)return;state.messages.push({role:"user",text:q});const a=answer(q);state.messages.push({role:"assistant",text:a.answer,source:a.section});save();renderMessages();renderHistory()}
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();ask($("#question").value);$("#question").value=""});$("#question").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#chatForm").requestSubmit()}});
function wireSuggestions(){document.querySelectorAll(".suggestions button").forEach(b=>b.onclick=()=>ask(b.textContent))}
function renderHistory(){const userQs=state.messages.filter(m=>m.role==="user");$("#historyList").innerHTML=userQs.length?userQs.slice(-8).reverse().map(m=>`<button class="history-item">${escapeHtml(m.text)}</button>`).join(""):`<div style="color:#657c8c;font-size:12px;padding:10px">لا توجد محادثات بعد</div>`}
$("#newChat").onclick=()=>{state.messages=[];save();renderMessages();renderHistory()};$("#clearHistory").onclick=()=>{if(confirm("هل تريد مسح سجل المحادثات؟")){state.messages=[];save();renderMessages();renderHistory()}};$("#logout").onclick=()=>{state.email="";state.messages=[];localStorage.removeItem("lumacare:lastUser");$("#appView").classList.add("hidden");$("#loginView").classList.remove("hidden")};
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
const last=localStorage.getItem("lumacare:lastUser");if(last&&allowedEmail.test(last))login(last);else wireSuggestions();

