const $=s=>document.querySelector(s);
const allowedEmail=/^[A-Z0-9._%+-]+@moh\.gov\.sa$/i;
const state={email:"",messages:[],lang:localStorage.getItem("lumacare:lang")||"ar"};
const knowledge=[
 {terms:["متى","متى يجب","متى يتم","قبل ماذا","وقت التحقق","توقيت التحقق","حالات التحقق","when","when should","when do","before what","verification timing","required to identify"],ar:"يجب التحقق من هوية المريض قبل تقديم أي رعاية أو تدخل. ويشمل ذلك قبل إعطاء الأدوية، وبدء الفحوصات أو العلاج، وسحب عينات سوائل الجسم، ونقل الدم ومشتقاته، والعمليات والإجراءات التدخلية، ونقل المريض، والأشعة والتصوير. كما يتم التحقق عند الدخول، وتُجرى مطابقة نهائية ضمن الـ Time-Out قبل بدء الإجراء مباشرة.",en:"Patient identity must be verified before any care or intervention. This includes medication administration, examinations or treatment, collection of body-fluid samples, blood or blood-product administration, surgery and invasive procedures, patient transfer, and imaging. Verification is also required at admission, with a final check during the Time-Out immediately before a procedure begins.",section:"Correct Patient Identification Policy — Sections 4.12, 4.14, 4.18 and 5.6"},
 {terms:["معرف","هويه","تحقق","تاكد","اسم","رقم السجل","رقم الملف","تاريخ الميلاد","identify","identification","identifier","verify","verification","full name","medical record","mrn","date of birth","dob","room number","bed number"],ar:"يجب التحقق من هوية المريض باستخدام معرّفين فريدين على الأقل. تشمل البيانات المعتمدة الاسم الكامل ورقم السجل الطبي، مع التحقق كذلك من تاريخ الميلاد والعمر حسب الإجراء. لا يجوز استخدام رقم الغرفة أو السرير للتعريف بالمريض.",en:"The patient must be identified using at least two unique identifiers. Approved details include the patient's full name and medical record number, with date of birth and age also checked as required. A room or bed number must never be used to identify a patient.",section:"Correct Patient Identification Policy — Sections 2.6, 3.5 and 4.3"},
 {terms:["رفض","يرفض","السوار","الاسوره","ارتداء","ما يبي","رفض المريض","refuse","refuses","refusal","wristband","id band","declines","does not want","will not wear"],ar:"إذا رفض المريض ارتداء سوار التعريف، يجب شرح المخاطر له وتوثيق النقاش وسبب الرفض في السجل الطبي. ثم تُستخدم وسيلة تعريف بديلة مناسبة بعد موافقة المريض أو قريبه، مع زيادة اليقظة قبل أي إجراء أو تدخل.",en:"If a patient refuses an identification wristband, explain the risks and document the discussion and reason for refusal in the health record. Use an appropriate alternative identification method with consent and apply increased vigilance before any procedure or intervention.",section:"Correct Patient Identification Policy — Sections 4.26.7 and 4.27"},
 {terms:["فاقد","وعي","مجهول","غيبوبه","ما يتكلم","غير معروف","لا يستجيب","unconscious","unknown patient","unresponsive","comatose","coma","cannot respond","unable to identify","trauma patient"],ar:"يُسجّل المريض المجهول أو فاقد الوعي بنظام ترقيم مثل UNKNOWN #1 متبوعًا برقم سجل طبي فريد، ويجب أن يرتدي سوار تعريف. إذا تعذر عليه تأكيد هويته، يتحقق ممرضَان مسجلان من الهوية قبل وضع السوار، ما لم يوجد ممثل يعرف المريض جيدًا.",en:"An unknown or unconscious patient is registered using a numbering system such as UNKNOWN #1 followed by a unique medical record number and must wear an identification wristband. If the patient cannot confirm their identity, two registered nurses verify it before the band is applied unless a representative who knows the patient is present.",section:"Correct Patient Identification Policy — Sections 4.9–4.11 and 4.26.5"},
 {terms:["نقل","تحويل","مسرح","عمليه","جراحه","تايم اوت","بين الاقسام","transfer","transport","operating theatre","operating room","surgery","surgical","time out","another facility","receiving staff"],ar:"عند النقل الداخلي يتحقق المستلم من سوار المريض ويراجع السجل الطبي. وعند استقبال مريض من منشأة أخرى يوضع سوار المنشأة المستقبلة فور وصوله ويزال السوار السابق. قبل الإجراء الجراحي يتم التحقق النهائي ضمن عملية الـ Time-Out.",en:"During an internal transfer, the receiving staff member checks the patient's wristband and reviews the medical record. A patient arriving from another facility receives the new facility's wristband immediately and the previous band is removed. Final verification is completed during the Time-Out immediately before a procedure.",section:"Correct Patient Identification Policy — Sections 4.15–4.18"}
 ,{terms:["طوارئ","الطوارئ","اسعاف","ملاحظه","انعاش","emergency","emergency department","ed patient","observation","resuscitation"],ar:"في قسم الطوارئ، يجب طباعة سوار التعريف أثناء التسجيل ووضعه فورًا لكل مريض يُوجّه إلى الملاحظة أو العلاج أو الإنعاش، بما في ذلك من ينتظر نقله من منطقة الإسعاف. أما الحالات المتنقلة أو البسيطة فيُستخدم السوار عند الحاجة المهنية أو قبل التهدئة الإجرائية أو حصار الأعصاب.",en:"In the Emergency Department, an identification wristband must be printed during registration and applied immediately for every patient directed to observation, treatment, or resuscitation, including patients awaiting movement from the ambulance bay. For ambulatory or minor-stream patients, a band is used when professionally appropriate or before procedural sedation or nerve blocks.",section:"Correct Patient Identification Policy — Sections 4.22.1–4.22.2"}
 ,{terms:["عياده","عيادات","خارجي","مراجع","موعد","استقبال","outpatient","clinic","appointment","check in","reception"],ar:"عند وصول المراجع للعيادة الخارجية وتسجيل حضوره، يطلب موظف الاستقبال من المريض أو مقدم الرعاية ذكر الاسم الكامل ورقم الهوية الوطنية أو الإقامة أو الجواز وتاريخ الميلاد، ثم يطابقها مع نظام المعلومات الصحية والملاحظات وبطاقة الموعد أو خطاب الإحالة. ويتحقق الفريق السريري من الهوية عند بداية كل فحص سريري.",en:"At outpatient arrival and check-in, reception asks the patient or caregiver to state the full name, National ID/Iqama/passport number, and date of birth, then validates these against the health information system, available notes, and appointment card or referral letter. Clinical staff verify identity again at the start of each clinical examination.",section:"Correct Patient Identification Policy — Sections 4.23.1–4.23.4"}
 ,{terms:["بدون سوار","ما عنده سوار","سوار مفقود","سوار تالف","مبلل","باهت","غير مقروء","استبدال السوار","without wristband","missing wristband","damaged band","wet band","faded band","unreadable band","replace wristband"],ar:"عند العثور على مريض بلا سوار، يُبلّغ الممرض المسؤول فورًا ليتم التحقق الصحيح من الهوية ووضع سوار جديد. وإذا أزيل السوار أو أصبح مبللًا أو باهتًا أو تالفًا أو غير مقروء، فيجب استبداله فورًا. وإذا تعذر الاستبدال الفوري، توضع وسيلة تعريف بديلة واضحة ويُوثق السبب في ملاحظات المريض.",en:"If a patient is found without a wristband, inform the assigned nurse immediately so the patient can be correctly identified and a new band applied. A removed, wet, faded, damaged, or unreadable band must be replaced immediately. If immediate replacement is impossible, establish a clear alternative identification method and document the reason in the patient notes.",section:"Correct Patient Identification Policy — Sections 4.28–4.29"}
];
const semantic={extractor:null,embeddings:null,loading:null,failed:false};
const semanticTexts=knowledge.map(item=>`passage: ${item.terms.join(". ")}. ${item.ar} ${item.en}`);
const ui={ar:{toggle:"English",assistant:"مساعد السياسات السريرية",status:"البحث المحلي جاهز — يتطور عند أول سؤال",source:"ملف معتمد",newChat:"＋ محادثة جديدة",history:"المحادثات",clear:"مسح",user:"مستخدم الوزارة",question:"اكتب سؤالك عن السياسات...",meta:"الإجابات من الملفات المعتمدة فقط",enter:"Enter للإرسال",welcome:"أهلًا بك في LumaCare",welcomeText:"اسأل عن سياسة التعرف الصحيح على المريض، وسأجيبك مع الإشارة إلى المصدر.",sourceLabel:"المصدر",empty:"لا توجد محادثات بعد"},en:{toggle:"العربية",assistant:"Clinical Policy Assistant",status:"Local search ready — improves on the first question",source:"Approved file",newChat:"＋ New conversation",history:"Conversations",clear:"Clear",user:"Ministry user",question:"Ask a question about the policies...",meta:"Answers use approved files only",enter:"Enter to send",welcome:"Welcome to LumaCare",welcomeText:"Ask about the Correct Patient Identification Policy and I will answer with a source reference.",sourceLabel:"Source",empty:"No conversations yet"}};
const loginUi={ar:{eyebrow:"المعرفة الأقرب لقرارك",badge:"بوابة مخصصة لمنسوبي وزارة الصحة",title:"ابحث في السياسات بثقة،<br><span>ووصل للمعلومة أسرع.</span>",copy:"مساعد معرفي يجيب من الملفات المعتمدة فقط، ويحتفظ بسجل محادثاتك للعودة إليه لاحقًا.",label:"بريد تسجيل الدخول",placeholder:"أكتب إيميلك الوظيفي",login:"الدخول إلى LumaCare",trust:["🔒 جلسة خاصة","◉ مصادر موثقة","✓ محفوظ تلقائيًا"]},en:{eyebrow:"Knowledge closer to your decision",badge:"A portal for Ministry of Health staff",title:"Search policies with confidence,<br><span>and reach answers faster.</span>",copy:"A knowledge assistant that answers only from approved files and keeps your conversation history for later.",label:"Login email",placeholder:"Enter your work email",login:"Sign in to LumaCare",trust:["🔒 Private session","◉ Cited sources","✓ Saved automatically"]}};
function applyLanguage(){const t=ui[state.lang],l=loginUi[state.lang];document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==="ar"?"rtl":"ltr";document.body.classList.toggle("english",state.lang==="en");$(".eyebrow").textContent=l.eyebrow;$(".security-badge").textContent=l.badge;$(".login-copy h2").innerHTML=l.title;$(".login-copy p").textContent=l.copy;$("label[for=email]").textContent=l.label;$("#email").placeholder=l.placeholder;$(".primary-button span:first-child").textContent=l.login;document.querySelectorAll(".trust-row span").forEach((x,i)=>x.textContent=l.trust[i]);$("#langToggle").textContent=t.toggle;$(".chat-header strong").textContent=t.assistant;$("#searchStatus").textContent=t.status;$(".source-count").innerHTML=`${t.source} <b>1</b>`;$("#newChat").textContent=t.newChat;$(".history-head span").textContent=t.history;$("#clearHistory").textContent=t.clear;$("#profileName").textContent=t.user;$("#question").placeholder=t.question;$(".composer-meta span:first-child").textContent=t.meta;$(".composer-meta span:last-child").textContent=t.enter;renderMessages();renderHistory()}
function key(email){return `lumacare:${email.toLowerCase()}`}
function save(){localStorage.setItem(key(state.email),JSON.stringify(state.messages))}
function load(){try{state.messages=JSON.parse(localStorage.getItem(key(state.email))||"[]")}catch{state.messages=[]}renderMessages();renderHistory()}
function login(email){state.email=email.toLowerCase();localStorage.setItem("lumacare:lastUser",state.email);$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#profileEmail").textContent=state.email;$("#avatar").textContent=state.email[0].toUpperCase();load()}
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();const email=$("#email").value.trim();if(!allowedEmail.test(email)){$("#emailError").textContent=state.lang==="ar"?"البريد غير مقبول":"Email not accepted";$("#emailField").classList.add("invalid");return}$("#emailError").textContent="";$("#emailField").classList.remove("invalid");login(email)});
$("#email").addEventListener("input",()=>{$("#emailError").textContent="";$("#emailField").classList.remove("invalid")});
function renderMessages(){const box=$("#messages"),t=ui[state.lang];if(!state.messages.length){const suggestions=state.lang==="ar"?["متى يجب التحقق من هوية المريض؟","ماذا نفعل إذا رفض المريض ارتداء سوار التعريف؟","كيف يتم تعريف المريض فاقد الوعي؟"]:["When must patient identity be verified?","What if a patient refuses an ID wristband?","How is an unconscious patient identified?"];box.innerHTML=`<article class="welcome-message"><div class="spark">✦</div><h2>${t.welcome}</h2><p>${t.welcomeText}</p><div class="suggestions">${suggestions.map(x=>`<button>${x}</button>`).join("")}</div></article>`;wireSuggestions();return}box.innerHTML=state.messages.map(m=>`<article class="message ${m.role}" dir="auto">${escapeHtml(m.text)}${m.source?`<span class="citation">${t.sourceLabel}: ${escapeHtml(m.source)}</span>`:""}</article>`).join("");box.scrollTop=box.scrollHeight}
function normalizeText(value){return value.toLowerCase().normalize("NFKD").replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[^a-z0-9\u0600-\u06ff\s]/g," ").replace(/\s+/g," ").trim()}
function isArabic(value){return (value.match(/[\u0600-\u06ff]/g)||[]).length>(value.match(/[a-z]/gi)||[]).length}
function lexicalMatch(q){const normalized=normalizeText(q);const words=normalized.split(" ").filter(w=>w.length>2);let index=-1,score=0;knowledge.forEach((item,i)=>{let s=0;for(const rawTerm of item.terms){const term=normalizeText(rawTerm);if(normalized.includes(term))s+=term.includes(" ")?4:2;else if(words.some(word=>term.length>3&&(word.startsWith(term.slice(0,4))||term.startsWith(word.slice(0,4)))))s+=1}if(s>score){score=s;index=i}});return{index,score}}
function resultFor(index,q){const item=knowledge[index];return{answer:isArabic(q)?item.ar:item.en,section:item.section}}
function noMatch(q){return isArabic(q)?{answer:"لم أجد إجابة مؤكدة لهذا السؤال في الملفات المعتمدة حاليًا. جرّب صياغة أخرى أو أرسل ملفًا يغطي الموضوع.",section:"لا يوجد مصدر مطابق"}:{answer:"I could not find a confirmed answer to this question in the currently approved files. Try another wording or provide a source document that covers the topic.",section:"No matching source"}}
function setSearchStatus(text,mode=""){$("#searchStatus").textContent=text;document.body.classList.remove("search-loading","search-ready");if(mode)document.body.classList.add(mode)}
async function prepareSemanticSearch(){if(semantic.embeddings||semantic.failed)return;if(semantic.loading)return semantic.loading;semantic.loading=(async()=>{try{setSearchStatus("جاري تهيئة البحث الذكي على جهازك…","search-loading");const {pipeline}=await import("https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2/+esm");semantic.extractor=await pipeline("feature-extraction","Xenova/multilingual-e5-small",{dtype:"q8"});const output=await semantic.extractor(semanticTexts,{pooling:"mean",normalize:true});semantic.embeddings=output.tolist();setSearchStatus("البحث الذكي المحلي جاهز","search-ready")}catch(error){console.warn("Semantic search unavailable; using local keyword search.",error);semantic.failed=true;setSearchStatus("البحث المحلي الأساسي جاهز")}})();return semantic.loading}
function cosine(a,b){let total=0;for(let i=0;i<a.length;i++)total+=a[i]*b[i];return total}
async function answer(q){const lexical=lexicalMatch(q);if(lexical.score>=2)return resultFor(lexical.index,q);await prepareSemanticSearch();if(!semantic.embeddings)return noMatch(q);try{const output=await semantic.extractor(`query: ${q}`,{pooling:"mean",normalize:true});const query=output.tolist()[0];const ranked=semantic.embeddings.map((embedding,index)=>({index,score:cosine(query,embedding)})).sort((a,b)=>b.score-a.score);if(ranked[0].score>=.79&&(ranked[0].score-ranked[1].score)>=.012)return resultFor(ranked[0].index,q)}catch(error){console.warn("Semantic query failed; no source match returned.",error)}return noMatch(q)}
async function ask(text){const q=text.trim();if(!q)return;state.messages.push({role:"user",text:q});save();renderMessages();renderHistory();const send=$("#sendButton");send.disabled=true;const a=await answer(q);state.messages.push({role:"assistant",text:a.answer,source:a.section});send.disabled=false;save();renderMessages();renderHistory();$("#question").focus()}
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();const input=$("#question");const value=input.value;input.value="";ask(value)});$("#question").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#chatForm").requestSubmit()}});
function wireSuggestions(){document.querySelectorAll(".suggestions button").forEach(b=>b.onclick=()=>ask(b.textContent))}
function renderHistory(){const userQs=state.messages.filter(m=>m.role==="user");$("#historyList").innerHTML=userQs.length?userQs.slice(-8).reverse().map(m=>`<button class="history-item" dir="auto">${escapeHtml(m.text)}</button>`).join(""):`<div style="color:#657c8c;font-size:12px;padding:10px">${ui[state.lang].empty}</div>`}
$("#newChat").onclick=()=>{state.messages=[];save();renderMessages();renderHistory()};$("#clearHistory").onclick=()=>{if(confirm("هل تريد مسح سجل المحادثات؟")){state.messages=[];save();renderMessages();renderHistory()}};$("#logout").onclick=()=>{state.email="";state.messages=[];localStorage.removeItem("lumacare:lastUser");$("#appView").classList.add("hidden");$("#loginView").classList.remove("hidden")};
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
$("#langToggle").onclick=()=>{state.lang=state.lang==="ar"?"en":"ar";localStorage.setItem("lumacare:lang",state.lang);applyLanguage()};const last=localStorage.getItem("lumacare:lastUser");if(last&&allowedEmail.test(last))login(last);applyLanguage();

